# All metrics are treated as gauge as the counter instrument don't provide a set
# method and for performance, it's always good to avoid calculation when ever it's possible.
# Using the inc() method require the diff to be calculated!
metrics = [
    ## Custom metrics
    ("up", "the status of the node (1=running, 0=down, -1=connection issue, -2=node error)"),
    ("peers_count", "how many peers the node is seeing"),
    ("sigs_count", "how many nodes are currently validating"),
    ("sigs_is_included", "if the node is currently validating"),
    ("header_nextValidators_count", "how many nodes are in the validators set for the next epoch"),
    ("header_nextValidators_is_included", "if the node is included in the next validators set"),
    ("header_nextValidators_stake_min", "the smallest amount of total stake in the validators set for the next epoch"),
    ("header_nextValidators_stake_max", "the biggest amount of total stake in the validators set for the next epoch"),

    ## /node/validator
    # ("validator_address", "validator_address"),
    ("validator_stakes_count", "the number of delegators currently staking on the node"),
    # ("validator_name", "validator_name"),
    ("validator_registered", "if the node is registered as validaator node"),
    ("validator_totalStake", "the total amount staked on the node"),
    # ("validator_url", "validator_url"),

    ## /system/peers
    #peers

    ## /system/epochproof
    # ("opaque", "opaque"),
    # ("sigs", "sigs"),
    # ("header_view", "header_view"),
    # ("header_nextValidators", "header_nextValidators"),
    # ("header_epoch", "header_epoch"),
    # ("header_accumulator", "header_accumulator"),
    # ("header_version", "header_version"),
    # ("header_timestamp", "header_timestamp"),

    ## /system/info
    # ("transports_0_metadata_port", "transports_0_metadata_port"),
    # ("transports_0_metadata_host", "transports_0_metadata_host"),
    # ("transports_0_sz", "transports_0_sz"),
    # ("transports_0_name", "transports_0_name"),
    # ("agent_protocol", "agent_protocol"),
    # ("agent_name", "agent_name"),
    # ("agent_version", "agent_version"),
    # ("hid", "hid"),
    # ("sz", "sz"),
    # ("nid", "nid"),
    # ("key", "key"),
    # ("info_counters_ledger_state_version", "info_counters_ledger_state_version"),
    ("info_counters_ledger_bft_commands_processed", "info_counters_ledger_bft_commands_processed"),
    ("info_counters_ledger_sync_commands_processed", "info_counters_ledger_sync_commands_processed"),
    ("info_counters_pacemaker_view", "info_counters_pacemaker_view"),
    ("info_counters_mempool_maxcount", "info_counters_mempool_maxcount"),
    ("info_counters_mempool_relayer_sent_count", "info_counters_mempool_relayer_sent_count"),
    ("info_counters_mempool_count", "info_counters_mempool_count"),
    ("info_counters_mempool_add_success", "info_counters_mempool_add_success"),
    ("info_counters_mempool_errors_other", "info_counters_mempool_errors_other"),
    ("info_counters_mempool_errors_hook", "info_counters_mempool_errors_hook"),
    ("info_counters_mempool_errors_conflict", "info_counters_mempool_errors_conflict"),
    ("info_counters_mempool_proposed_transaction", "info_counters_mempool_proposed_transaction"),
    ("info_counters_radix_engine_invalid_proposed_commands", "info_counters_radix_engine_invalid_proposed_commands"),
    ("info_counters_radix_engine_system_transactions", "info_counters_radix_engine_system_transactions"),
    ("info_counters_radix_engine_user_transactions", "info_counters_radix_engine_user_transactions"),
    ("info_counters_count_bdb_ledger_contains_tx", "info_counters_count_bdb_ledger_contains_tx"),
    ("info_counters_count_bdb_ledger_deletes", "info_counters_count_bdb_ledger_deletes"),
    ("info_counters_count_bdb_ledger_commit", "info_counters_count_bdb_ledger_commit"),
    ("info_counters_count_bdb_ledger_save", "info_counters_count_bdb_ledger_save"),
    ("info_counters_count_bdb_ledger_last_vertex", "info_counters_count_bdb_ledger_last_vertex"),
    ("info_counters_count_bdb_ledger_store", "info_counters_count_bdb_ledger_store"),
    ("info_counters_count_bdb_ledger_create_tx", "info_counters_count_bdb_ledger_create_tx"),
    ("info_counters_count_bdb_ledger_contains", "info_counters_count_bdb_ledger_contains"),
    ("info_counters_count_bdb_ledger_entries", "info_counters_count_bdb_ledger_entries"),
    ("info_counters_count_bdb_ledger_get_last", "info_counters_count_bdb_ledger_get_last"),
    ("info_counters_count_bdb_ledger_get_next", "info_counters_count_bdb_ledger_get_next"),
    ("info_counters_count_bdb_ledger_search", "info_counters_count_bdb_ledger_search"),
    ("info_counters_count_bdb_ledger_total", "info_counters_count_bdb_ledger_total"),
    ("info_counters_count_bdb_ledger_get_prev", "info_counters_count_bdb_ledger_get_prev"),
    ("info_counters_count_bdb_ledger_bytes_read", "info_counters_count_bdb_ledger_bytes_read"),
    ("info_counters_count_bdb_ledger_bytes_write", "info_counters_count_bdb_ledger_bytes_write"),
    ("info_counters_count_bdb_ledger_proofs_removed", "info_counters_count_bdb_ledger_proofs_removed"),
    ("info_counters_count_bdb_ledger_proofs_added", "info_counters_count_bdb_ledger_proofs_added"),
    ("info_counters_count_bdb_ledger_get", "info_counters_count_bdb_ledger_get"),
    ("info_counters_count_bdb_ledger_last_committed", "info_counters_count_bdb_ledger_last_committed"),
    ("info_counters_count_bdb_ledger_get_first", "info_counters_count_bdb_ledger_get_first"),
    ("info_counters_count_bdb_header_bytes_write", "info_counters_count_bdb_header_bytes_write"),
    ("info_counters_count_bdb_address_book_deletes", "info_counters_count_bdb_address_book_deletes"),
    ("info_counters_count_bdb_address_book_total", "info_counters_count_bdb_address_book_total"),
    ("info_counters_count_bdb_address_book_bytes_read", "info_counters_count_bdb_address_book_bytes_read"),
    ("info_counters_count_bdb_address_book_bytes_write", "info_counters_count_bdb_address_book_bytes_write"),
    ("info_counters_count_bdb_safety_state_total", "info_counters_count_bdb_safety_state_total"),
    ("info_counters_count_bdb_safety_state_bytes_read", "info_counters_count_bdb_safety_state_bytes_read"),
    ("info_counters_count_bdb_safety_state_bytes_write", "info_counters_count_bdb_safety_state_bytes_write"),
    ("info_counters_count_apidb_balance_total", "info_counters_count_apidb_balance_total"),
    ("info_counters_count_apidb_balance_read", "info_counters_count_apidb_balance_read"),
    ("info_counters_count_apidb_balance_bytes_read", "info_counters_count_apidb_balance_bytes_read"),
    ("info_counters_count_apidb_balance_bytes_write", "info_counters_count_apidb_balance_bytes_write"),
    ("info_counters_count_apidb_balance_write", "info_counters_count_apidb_balance_write"),
    ("info_counters_count_apidb_flush_count", "info_counters_count_apidb_flush_count"),
    ("info_counters_count_apidb_queue_size", "info_counters_count_apidb_queue_size"),
    ("info_counters_count_apidb_transaction_total", "info_counters_count_apidb_transaction_total"),
    ("info_counters_count_apidb_transaction_read", "info_counters_count_apidb_transaction_read"),
    ("info_counters_count_apidb_transaction_bytes_read", "info_counters_count_apidb_transaction_bytes_read"),
    ("info_counters_count_apidb_transaction_bytes_write", "info_counters_count_apidb_transaction_bytes_write"),
    ("info_counters_count_apidb_transaction_write", "info_counters_count_apidb_transaction_write"),
    ("info_counters_count_apidb_token_total", "info_counters_count_apidb_token_total"),
    ("info_counters_count_apidb_token_read", "info_counters_count_apidb_token_read"),
    ("info_counters_count_apidb_token_bytes_read", "info_counters_count_apidb_token_bytes_read"),
    ("info_counters_count_apidb_token_bytes_write", "info_counters_count_apidb_token_bytes_write"),
    ("info_counters_count_apidb_token_write", "info_counters_count_apidb_token_write"),
    ("info_counters_epoch_manager_queued_consensus_events", "info_counters_epoch_manager_queued_consensus_events"),
    ("info_counters_hashed_bytes", "info_counters_hashed_bytes"),
    ("info_counters_networking_received_bytes", "info_counters_networking_received_bytes"),
    ("info_counters_networking_tcp_out_opened", "info_counters_networking_tcp_out_opened"),
    ("info_counters_networking_tcp_dropped_messages", "info_counters_networking_tcp_dropped_messages"),
    ("info_counters_networking_tcp_in_opened", "info_counters_networking_tcp_in_opened"),
    ("info_counters_networking_tcp_closed", "info_counters_networking_tcp_closed"),
    ("info_counters_networking_udp_dropped_messages", "info_counters_networking_udp_dropped_messages"),
    ("info_counters_networking_sent_bytes", "info_counters_networking_sent_bytes"),
    ("info_counters_sync_processed", "info_counters_sync_processed"),
    ("info_counters_sync_target_state_version", "info_counters_sync_target_state_version"),
    ("info_counters_sync_remote_requests_processed", "info_counters_sync_remote_requests_processed"),
    ("info_counters_sync_invalid_commands_received", "info_counters_sync_invalid_commands_received"),
    ("info_counters_sync_last_read_millis", "info_counters_sync_last_read_millis"),
    ("info_counters_sync_target_current_diff", "info_counters_sync_target_current_diff"),
    ("info_counters_signatures_verified", "info_counters_signatures_verified"),
    ("info_counters_signatures_signed", "info_counters_signatures_signed"),
    ("info_counters_elapsed_bdb_ledger_contains_tx", "info_counters_elapsed_bdb_ledger_contains_tx"),
    ("info_counters_elapsed_bdb_ledger_commit", "info_counters_elapsed_bdb_ledger_commit"),
    ("info_counters_elapsed_bdb_ledger_save", "info_counters_elapsed_bdb_ledger_save"),
    ("info_counters_elapsed_bdb_ledger_last_vertex", "info_counters_elapsed_bdb_ledger_last_vertex"),
    ("info_counters_elapsed_bdb_ledger_store", "info_counters_elapsed_bdb_ledger_store"),
    ("info_counters_elapsed_bdb_ledger_create_tx", "info_counters_elapsed_bdb_ledger_create_tx"),
    ("info_counters_elapsed_bdb_ledger_contains", "info_counters_elapsed_bdb_ledger_contains"),
    ("info_counters_elapsed_bdb_ledger_entries", "info_counters_elapsed_bdb_ledger_entries"),
    ("info_counters_elapsed_bdb_ledger_get_last", "info_counters_elapsed_bdb_ledger_get_last"),
    ("info_counters_elapsed_bdb_ledger_search", "info_counters_elapsed_bdb_ledger_search"),
    ("info_counters_elapsed_bdb_ledger_total", "info_counters_elapsed_bdb_ledger_total"),
    ("info_counters_elapsed_bdb_ledger_get", "info_counters_elapsed_bdb_ledger_get"),
    ("info_counters_elapsed_bdb_ledger_last_committed", "info_counters_elapsed_bdb_ledger_last_committed"),
    ("info_counters_elapsed_bdb_ledger_get_first", "info_counters_elapsed_bdb_ledger_get_first"),
    ("info_counters_elapsed_bdb_address_book", "info_counters_elapsed_bdb_address_book"),
    ("info_counters_elapsed_bdb_safety_state", "info_counters_elapsed_bdb_safety_state"),
    ("info_counters_elapsed_apidb_balance_read", "info_counters_elapsed_apidb_balance_read"),
    ("info_counters_elapsed_apidb_balance_write", "info_counters_elapsed_apidb_balance_write"),
    ("info_counters_elapsed_apidb_flush_time", "info_counters_elapsed_apidb_flush_time"),
    ("info_counters_elapsed_apidb_transaction_read", "info_counters_elapsed_apidb_transaction_read"),
    ("info_counters_elapsed_apidb_transaction_write", "info_counters_elapsed_apidb_transaction_write"),
    ("info_counters_elapsed_apidb_token_read", "info_counters_elapsed_apidb_token_read"),
    ("info_counters_elapsed_apidb_token_write", "info_counters_elapsed_apidb_token_write"),
    ("info_counters_bft_state_version", "info_counters_bft_state_version"),
    ("info_counters_bft_vote_quorums", "info_counters_bft_vote_quorums"),
    ("info_counters_bft_rejected", "info_counters_bft_rejected"),
    ("info_counters_bft_vertex_store_rebuilds", "info_counters_bft_vertex_store_rebuilds"),
    ("info_counters_bft_vertex_store_forks", "info_counters_bft_vertex_store_forks"),
    ("info_counters_bft_sync_request_timeouts", "info_counters_bft_sync_request_timeouts"),
    ("info_counters_bft_sync_requests_sent", "info_counters_bft_sync_requests_sent"),
    ("info_counters_bft_timeout", "info_counters_bft_timeout"),
    ("info_counters_bft_vertex_store_size", "info_counters_bft_vertex_store_size"),
    ("info_counters_bft_processed", "info_counters_bft_processed"),
    ("info_counters_bft_consensus_events", "info_counters_bft_consensus_events"),
    ("info_counters_bft_indirect_parent", "info_counters_bft_indirect_parent"),
    ("info_counters_bft_proposals_made", "info_counters_bft_proposals_made"),
    ("info_counters_bft_timed_out_views", "info_counters_bft_timed_out_views"),
    ("info_counters_bft_timeout_quorums", "info_counters_bft_timeout_quorums"),
    ("info_counters_startup_time_ms", "info_counters_startup_time_ms"),
    ("info_counters_messages_inbound_processed", "info_counters_messages_inbound_processed"),
    ("info_counters_messages_inbound_discarded", "info_counters_messages_inbound_discarded"),
    ("info_counters_messages_inbound_badsignature", "info_counters_messages_inbound_badsignature"),
    ("info_counters_messages_inbound_received", "info_counters_messages_inbound_received"),
    ("info_counters_messages_outbound_processed", "info_counters_messages_outbound_processed"),
    ("info_counters_messages_outbound_aborted", "info_counters_messages_outbound_aborted"),
    ("info_counters_messages_outbound_pending", "info_counters_messages_outbound_pending"),
    ("info_counters_messages_outbound_sent", "info_counters_messages_outbound_sent"),
    ("info_counters_persistence_safety_store_saves", "info_counters_persistence_safety_store_saves"),
    ("info_counters_persistence_vertex_store_saves", "info_counters_persistence_vertex_store_saves"),
    ("info_counters_persistence_atom_log_write_bytes", "info_counters_persistence_atom_log_write_bytes"),
    ("info_counters_persistence_atom_log_write_compressed", "info_counters_persistence_atom_log_write_compressed"),
    ("info_counters_time_duration", "info_counters_time_duration"),
    # ("info_counters_time_since", "info_counters_time_since"),
    ("info_configuration_pacemakerRate", "info_configuration_pacemakerRate"),
    ("info_configuration_pacemakerTimeout", "info_configuration_pacemakerTimeout"),
    ("info_configuration_pacemakerMaxExponent", "info_configuration_pacemakerMaxExponent"),
    ("info_system_version_system_version_agent_version", "info_system_version_system_version_agent_version"),
    ("info_system_version_system_version_protocol_version", "info_system_version_system_version_protocol_version"),
    # ("info_system_version_system_version_display", "info_system_version_system_version_display"),
    # ("info_system_version_system_version_commit", "info_system_version_system_version_commit"),
    # ("info_system_version_system_version_branch", "info_system_version_system_version_branch"),
    ("info_epochManager_currentView_view", "info_epochManager_currentView_view"),
    ("info_epochManager_currentView_epoch", "info_epochManager_currentView_epoch"),
]
